spring:
  datasource:
    url: jdbc:mysql://45.145.229.186:3306/test1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: test1
    password: M7p3XNGK6HD2EBWK
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 1234
